[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "3D terrain generation"
edition = "2018"
license = "MIT"
name = "terra"
repository = "https://github.com/LucasPickering/terra-rs"
version = "0.1.0"

[package.metadata.wasm-pack]
target = "web"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
console_error_panic_hook = "0.1"
js-sys = "0.3"
kiss3d = "0.28"
log = "0.4"
# nalgebra needs to stay the same as kiss3d's version
nalgebra = "0.23"
noise = "0.6"
serde = {version = "1.0", features = ["derive"]}
wasm-bindgen = {version = "0.2", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"

[dependencies.web-sys]
features = ["Window", "Headers", "Request", "RequestInit", "RequestMode", "Response"]
version = "0.3"
