[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
edition = "2018"
name = "terra"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
console_error_panic_hook = "0.1"
env_logger = "0.7"
kiss3d = "0.28"
log = "0.4"
# nalgebra needs to stay the same as kiss3d's version
nalgebra = "0.23"
noise = "0.6"
serde = {version = "1.0", features = ["derive"]}
three = "0.4"
wasm-bindgen = "0.2"
wasm-logger = "0.2"

[dependencies.config]
default-features = false
features = ["toml"]
version = "^0.10.1"
