[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "3D terrain generation"
edition = "2018"
license = "MIT"
name = "terra"
repository = "https://github.com/LucasPickering/terra-rs"
version = "0.1.0"

[package.metadata.wasm-pack.profile.profiling]
# workaround to get debug info in
wasm-opt = ['-O4', '-g']

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
cgmath = "0.17"
console_error_panic_hook = "0.1"
gloo = "0.2"
js-sys = "0.3"
log = "0.4"
luminance = "0.43"
luminance-front = "0.3"
luminance-web-sys = "0.2"
noise = "0.6"
rand = "0.7"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
wasm-bindgen = {version = "0.2", features = ["serde-serialize"]}
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"

[dependencies.web-sys]
features = [
  "Window",
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "EventListener",
  "KeyboardEvent",
]
version = "0.3.40"
