[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "3D rendering for Terra worlds"
edition = "2021"
license = "MIT"
name = "terra-3d"
repository = "https://github.com/LucasPickering/terra-rs"
version = "0.1.0"

[dependencies]
bevy = {version = "0.9.1", default-features = false, features = [
  # We can't use `dynamic` because it doesn't work in wasm :(
  "bevy_asset",
  "bevy_winit",
  "filesystem_watcher",
  "render",
  "x11",
]}
bevy-inspector-egui = "0.14.0"
bevy_common_assets = {version = "0.4.0", features = ["json"]}
terra = {path = "../core", features = ["bevy"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
