name: Build Artifacts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        # The packages that we want to build binaries for
        package:
          - terra-cli
          - terra-3d
        # The platforms we want to distribute to
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          # TODO fix this build and re-enable
          # - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust files
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.package }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Build release binaries
        id: build
        shell: bash # Makes it work on windows
        run: |
          cargo build --package ${{ matrix.package }} --verbose --release --target ${{ matrix.target }} --message-format=json | tee cargo-output.txt
          # Grab the path of the binary and store it for later
          echo "BINARY_FILE=$(jq -r '.executable | select(. != null)' cargo-output.txt)" >> $GITHUB_OUTPUT

      # Just a debug step to make sure we read the path correctly
      - name: List binary
        run: echo "${{ steps.build.outputs.BINARY_FILE }}"

      - name: Strip binary(Unix only)
        if: contains(matrix.target, 'linux') || contains(matrix.target, 'apple')
        run: strip ${{ steps.build.outputs.BINARY_FILE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-${{ matrix.target }}
          path: ${{ steps.build.outputs.BINARY_FILE }}
          if-no-files-found: error
