name: Lint, Test, Build, and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Clippy, Rustfmt, & Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Install dependencies
        run: |
          rustup component add rustfmt clippy
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  build-and-deploy-ts:
    name: "Build TS app, & Deploy if on master"
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Cache cargo & npm files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            typescript/node_modules
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('Cargo.lock', 'typescript/package-lock.json') }}

      - name: Install Toolchain
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          cd typescript
          npm install
          npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: typescript/dist
          CLEAN: true
