name: Build and Deploy Demo

on:
  workflow_run:
    workflows: ["Lint and Test"]
    branches: [master]
    types: [completed]

jobs:
  deploy-demo:
    name: "Deploy demo"
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: demo-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: typescript/dist
          CLEAN: true
